[package]
name = "example-axum"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../../" }
rspc-axum = { path = "../../crates/axum", features = ["ws"] }
tokio = { version = "1.41.1", features = ["full"] }
async-stream = "0.3.6"
axum = { version = "0.7.9", features = ["ws"] }
tower-http = { version = "0.6.2", default-features = false, features = [
    "cors",
] }
specta-typescript = "0.0.7"
serde = { version = "1.0.215", features = ["derive"] }
specta = { version = "=2.0.0-rc.20", features = [
    "derive",
] } # TODO: Drop all features
