[package]
name = "rspc-invalidation"
version = "0.0.0"
edition = "2021"
publish = false # TODO: Crate metadata & publish

[dependencies]
async-stream = "0.3.6"
rspc = { path = "../../rspc", features = ["unstable"] }
serde = "1.0.216"
serde_json = "1.0.134"

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
