[package]
name = "rspc-http"
description = "Generic HTTP adapter for rspc"
version = "0.2.1"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/specta-rs/rspc"
documentation = "https://docs.rs/rspc-axum/latest/rspc-axum"
keywords = ["async", "specta", "rust-to-ts", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
rspc-core = { version = "0.0.1", path = "../../core" }
serde_json = "1"
form_urlencoded = "1"
futures-core = "0.3"

futures = "0.3" # TODO: Remove this
erased-serde = "0.4.5"
serde = "1.0.216"

[lints]
workspace = true
