[package]
name = "example-client"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc-client = { path = "../../crates/client" }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
