[package]
name = "example-legacy"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
rspc = { path = "../../rspc", features = ["typescript", "rust", "legacy"] }
rspc-axum = { path = "../../integrations/axum", features = ["ws"] }
rspc-legacy = { path = "../../crates/legacy" }
axum = { version = "0.8.1", features = ["multipart"] }
tower-http = { version = "0.6.2", default-features = false, features = [
    "cors",
] }
futures.workspace = true
serde_json.workspace = true
async-stream = "0.3.6"
