[package]
name = "example-anyhow"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../../rspc", features = ["typescript"] }
specta.workspace = true
anyhow = "1.0.95"
thiserror = "2.0.11"

[lints]
workspace = true
