[package]
name = "rspc-devtools"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc-core = { path = "../../core" }
serde = { version = "1.0.215", features = ["derive"] }
specta = { version = "=2.0.0-rc.20", features = ["derive"] }

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
